javaApp:
  namespace: default
  name: appName
  version: 1.0.0
  #serviceAccount: serviceaccount-name 
  group: com.stackator
  deployment:
    minReadySeconds: 5
    replicaCount: 2
    revisionHistoryLimit: 2
    # probes:
    #   liveness:
    #     failureThreshold: 5
    #     periodSeconds: 10
    #     successThreshold: 1
    #     timeoutSeconds: 1
    #     path: /health
    #     port: 8080
    #     scheme: HTTP
    #     initialDelaySeconds: 180
    #   readiness:
    #     failureThreshold: 5
    #     periodSeconds: 10
    #     successThreshold: 1
    #     timeoutSeconds: 1
    #     path: /health
    #     port: 8080
    #     scheme: HTTP
    #     initialDelaySeconds: 10
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "1"
    #   requests:
    #     memory: "64Mi"
    #     cpu: "0.5"
  service:
    #ingressPath: /vis/
    #rewriteTarget: /
    ingressClass: external-ingress
    forceSslRedirect: true
    prometheusPort: 9779
    prometheusScrape: true
    expose: true
    #additionalIngressAnnotations:
    #  - key: monitor.stakater.com/enabled
    #    value: true
    # ports:
    #   - name: http
    #     port: 8080
    #     protocol: TCP
    #     targetPort: 8080
  image:
    name: imageName
    tag: "tag"
    pullPolicy: IfNotPresent

  # rollingUpdateStrategy:
  #   strategy:
  #     rollingUpdate:
  #       maxSurge: 1
  #       maxUnavailable: 1
  #     type: RollingUpdate

  # mounts:
  #   secrets:
  #   - mountName: mountName
  #     mountPath: /some/path
  #     secretName: some-secret
  #   - mountName: mountName2
  #     mountPath: /some/path2
  #     secretName: some-secret2
  #     readOnly: true
  #   hostPaths:
  #   - mountName: name
  #     mountPath: /path
  #     hostPath: /host/path
  
  # env:
  # - name: key1
  #   value: value1
  # - name: key2
  #   value: value2
  # - name: key3
  #   value: value3

  # ports:
  # - containerPort: 8080
  #   name: http
  #   protocol: TCP
  # - containerPort: 9779
  #   name: prometheus
  #   protocol: TCP
  # - containerPort: 8778
  #   name: jolokia
  #   protocol: TCP
    
  imagePullSecrets:
    - image-pull-secret
    