javaApp:
  namespace: default
  name: appName
  version: 1.0.0
  #serviceAccount: serviceaccount-name 
  labels:
    group: com.stakater.platform
    provider: stakater
  tolerations: {}
  deployment:
    minReadySeconds: 5
    replicaCount: 2
    revisionHistoryLimit: 2
    # podAnnotations:
    #   - key: myannotationkey
    #     value: myannotationvalue
    # probes:
    #   liveness:
    #     failureThreshold: 5
    #     periodSeconds: 10
    #     successThreshold: 1
    #     timeoutSeconds: 1
    #     path: /health
    #     port: 8080
    #     scheme: HTTP
    #     initialDelaySeconds: 180
    #   readiness:
    #     failureThreshold: 5
    #     periodSeconds: 10
    #     successThreshold: 1
    #     timeoutSeconds: 1
    #     path: /health
    #     port: 8080
    #     scheme: HTTP
    #     initialDelaySeconds: 10
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "1"
    #   requests:
    #     memory: "64Mi"
    #     cpu: "0.5"
  service:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
      config.xposer.stakater.com/Domain: stackator.com
      config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-{{.Namespace}}'
      config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}.{{.Namespace}}.{{.Domain}}'
      config.xposer.stakater.com/TLS: "true"
      xposer.stakater.com/annotations: |-
        kubernetes.io/ingress.class: external-ingress
        ingress.kubernetes.io/force-ssl-redirect: true
        monitor.stakater.com/enabled: true
     
    #config.xposer.stakater.com/IngressURLPath: "/vis/"
    #    ingress.kubernetes.io/rewrite-target: /
    expose: true
    # ports:
    #   - name: http
    #     port: 8080
    #     protocol: TCP
    #     targetPort: 8080
  image:
    name: imageName
    tag: "tag"
    pullPolicy: IfNotPresent

  # rollingUpdateStrategy:
  #   strategy:
  #     rollingUpdate:
  #       maxSurge: 1
  #       maxUnavailable: 1
  #     type: RollingUpdate

  # mounts:
  #   secrets:
  #   - mountName: mountName
  #     mountPath: /some/path
  #     secretName: some-secret
  #   - mountName: mountName2
  #     mountPath: /some/path2
  #     secretName: some-secret2
  #     readOnly: true
  #   hostPaths:
  #   - mountName: name
  #     mountPath: /path
  #     hostPath: /host/path
  
  # env:
  # - name: key1
  #   value: value1
  # - name: key2
  #   value: value2
  # - name: key3
  #   value: value3

  # ports:
  # - containerPort: 8080
  #   name: http
  #   protocol: TCP
  # - containerPort: 9779
  #   name: prometheus
  #   protocol: TCP
  # - containerPort: 8778
  #   name: jolokia
  #   protocol: TCP
    
  imagePullSecrets:
    - image-pull-secret
  
  # config:
  #   fluentd:
  #     regex: hello
  #     timeFormat: world