---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: {{ .Values.javaApp.name }}
      version: {{ .Values.javaApp.version }}
      group: {{ .Values.javaApp.group }}
    name: {{ .Values.javaApp.name }}
  spec:
  {{- with .Values.javaApp.deployment.minReadySeconds }}
    minReadySeconds: {{ . }}
  {{- end }}
    replicas: {{ .Values.javaApp.deployment.replicaCount }}
    revisionHistoryLimit: {{ .Values.javaApp.deployment.revisionHistoryLimit }}
    selector:
      matchLabels:
        app: {{ .Values.javaApp.name }}
        version: {{ .Values.javaApp.version }}
        group: {{ .Values.javaApp.group }}
{{- with .Values.javaApp.rollingUpdateStrategy }}
{{ toYaml . | indent 4 -}}
{{- end }}
    template:
      metadata:
        labels:
          app: {{ .Values.javaApp.name }}
          version: {{ .Values.javaApp.version }}
          group: {{ .Values.javaApp.group }}
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- with .Values.javaApp.env }}
            {{- range . }}
          - name: {{ .name }}
            value: "{{ .value }}"
            {{- end }}
          {{- end }}
          image: "{{ .Values.javaApp.image.name }}:{{ .Values.javaApp.image.tag }}"
          imagePullPolicy: {{ .Values.javaApp.image.pullPolicy }}
          {{- with .Values.javaApp.deployment.probes }}
          {{- with .liveness }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
              scheme: {{ .scheme }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
          {{- end }}
          {{- end }}
          name: spring-boot
          {{- with .Values.javaApp.ports }}
          ports:
            {{- range . }}
          - containerPort: {{ .containerPort }}
            name: {{ .name }}
            protocol: {{ .protocol }}
            {{- end }}
          {{- end }}
          {{- with .Values.javaApp.deployment.probes }}
          {{- with .readiness }}
          readinessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
              scheme: {{ .scheme }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
          {{- end }}
          {{- end }}
          securityContext:
            privileged: false
          {{- with .Values.javaApp.mounts }}
          volumeMounts:
            {{- with .secrets }}
              {{- range . }}
          - mountPath: {{ .mountPath }}
            name: {{ .mountName }}
            {{- with .readOnly }}
            readOnly: {{ . }}
            {{- end }}
              {{- end }}
            {{- end }}
          {{- with .hostPaths }}
              {{- range . }}
          - mountPath: {{ .mountPath }}
            name: {{ .mountName }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- with .Values.javaApp.imagePullSecrets }}
        imagePullSecrets:
          {{- range . }}
        - name: {{ . }}
          {{- end }}
        {{- end }}
        {{- with .Values.javaApp.serviceAccount }}
        serviceAccount: {{ . }}
        {{- end }}
        {{- with .Values.javaApp.mounts }}
        volumes:
          {{- range .secrets }}
        - name: {{ .mountName }}
          secret:
            secretName: {{ .secretName }}
          {{- end }}
          {{- range .hostPaths }}
        - name: {{ .mountName }}
          hostPath:
            path: {{ .hostPath }}
          {{- end }}
        {{- end }}