---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      {{- if .Values.javaApp.service.ingressPath }}
      fabric8.io/ingress.path: {{ .Values.javaApp.service.ingressPath }}
      {{- end }}
      fabric8.io/ingress.annotations: |-
        {{- if .Values.javaApp.service.rewriteTarget }}
        ingress.kubernetes.io/rewrite-target: {{ .Values.javaApp.service.rewriteTarget }}
        {{- end }}
        ingress.kubernetes.io/force-ssl-redirect: true
        kubernetes.io/ingress.class: {{ .Values.javaApp.service.ingressClass }}
      prometheus.io/port: {{ .Values.javaApp.service.prometheusPort | quote }}
      prometheus.io/scrape: {{ .Values.javaApp.service.prometheusScrape | quote }}
    labels:
      expose: "true"
      app: {{ .Values.javaApp.name }}
      provider: fabric8
      version: {{ .Values.javaApp.version }}
      group: com.scania.dd
    name: {{ .Values.javaApp.name }}
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: {{ .Values.javaApp.name }}
      provider: fabric8
      group: com.scania.dd
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: {{ .Values.javaApp.name }}
      provider: fabric8
      version: {{ .Values.javaApp.version }}
      group: com.scania.dd
    name: {{ .Values.javaApp.name }}
  spec:
  {{- if .Values.javaApp.service.minReadySeconds }}
    minReadySeconds: {{ .Values.javaApp.service.minReadySeconds }}
  {{- end }}
    replicas: {{ .Values.javaApp.service.replicaCount }}
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: {{ .Values.javaApp.name }}
        provider: fabric8
        group: com.scania.dd
{{- if .Values.javaApp.rollingUpdateStrategy }}
{{ toYaml .Values.javaApp.rollingUpdateStrategy | indent 4 -}}
{{- end }}
    template:
      metadata:
        labels:
          app: {{ .Values.javaApp.name }}
          provider: fabric8
          version: {{ .Values.javaApp.version }}
          group: com.scania.dd
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JAVA_APP_JAR
            value: "{{ .Values.javaApp.name }}-{{ .Values.javaApp.version }}.jar"
          image: "{{ .Values.javaApp.image.name }}:{{ .Values.javaApp.image.tag }}"
          imagePullPolicy: {{ .Values.javaApp.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
          {{- if .Values.javaApp.mountSecrets }}
          volumeMounts:
            {{- range .Values.javaApp.mountSecrets }}
          - mountPath: {{ .mountPath }}
            name: {{ .mountName }}
            readOnly: true
            {{- end }}
          {{- end }}
        {{- if .Values.javaApp.imagePullSecrets }}
        imagePullSecrets:
          {{- range .Values.javaApp.imagePullSecrets }}
        - name: {{ . }}
          {{- end }}
        {{- end }}
        {{- if .Values.javaApp.serviceAccount }}
        serviceAccount: {{ .Values.javaApp.serviceAccount }}
        {{- end }}
        {{- if .Values.javaApp.mountSecrets }}
        volumes:
          {{- range .Values.javaApp.mountSecrets }}
        - name: {{ .mountName }}
          secret:
            secretName: {{ .secretName }}
          {{- end }}
        {{- end }}