{{- with .Values.javaApp.service }}
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      {{- with .ingressPath }}
      fabric8.io/ingress.path: {{ . }}
      {{- end }}
      fabric8.io/ingress.annotations: |-
        {{- with .rewriteTarget }}
        ingress.kubernetes.io/rewrite-target: {{ . }}
        {{- end }}
        ingress.kubernetes.io/force-ssl-redirect: {{ .forceSslRedirect }}
        kubernetes.io/ingress.class: {{ .ingressClass }}
        {{- with .additionalIngressAnnotations }}
        {{- range . }}
        {{ .key }}: {{ .value }}
        {{- end }}
        {{- end }}
      prometheus.io/port: {{ .prometheusPort | quote }}
      prometheus.io/scrape: {{ .prometheusScrape | quote }}
    labels:
      expose: {{ .expose | quote }}
{{ include "labels.stakater" $ | indent 6 }}
{{ include "labels.chart" $ | indent 6 }}
    name: {{ $.Values.javaApp.name }}
  spec:
    ports:
    {{- range .ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
    {{- end }}
    selector:
{{ include "labels.selector" $ | indent 6 }}
{{- end }}